services:
  db:
    image: postgres:16.0-alpine
    networks:
      - deployment
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: dbo-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty123

  app:
    image: alionamak/myapp:1.0.0
    networks:
      - deployment
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: preprod
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/dbo-db'
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: qwerty123

networks:
  deployment:
